[profile.default]
src = 'contracts'
out = 'out'
libs = [
    'lib'
]
ffi=true
verbosity=5

remappings = [
    @openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/,
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config